const ADD_TO_CART = 'ADD_TO_CART'
const REMOVE_ITEMS = 'REMOVE_ITEMS'
const UPDATE_QUANTITY = 'UPDATE_QUANTITY'
const EMPTY_STORE = 'EMPTY_STORE'

export{ADD_TO_CART,REMOVE_ITEMS,UPDATE_QUANTITY,EMPTY_STORE}